version: '3.4'

services:
  github_search_app:
    container_name: github_search_app
    image: github_search_app
    networks:
      - github_search_net
    depends_on:
      - github_search_db
    build:
      context: ./services/github_search
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./services/github_search/:/opt/app/services/github_search

  github_search_db: 
    container_name: github_search_db
    image: postgres:latest
    environment:
      POSTGRES_USER: franchel
      POSTGRES_DB: github_projects
      POSTGRES_HOST_AUTH_METHOD: trust  # Позволяет подключаться без пароля
    networks:
      - github_search_net
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  github_search_net:
    driver: bridge

    # sample_microservice:
  #   container_name: sample_microservice
  #   image: sample_microservice
  #   build:
  #     context: ./services/sample_microservice
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./services/sample_microservice/:/opt/app/services/sample_microservice
  #     - /opt/app/services/sample_microservice/node_modules