version: '3.4'

services:
  jslevitest:
    image: jslevitest
    build:
      context: services/js_levi_test
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
